import MediaIcon from './MediaIcon.svg';
import WatchIcon from './WatchIcon.svg';
import MoreIcon from './MoreIcon.svg';
import DashboardIcon from './DashboardIcon.svg';
import SearchIcon from './SearchIcon.svg';
import BackIcon from './BackIcon.svg';
import PlayIcon from './PlayIcon.svg';
import CloseIcon from './CloseIcon.svg';
import Dots from './3dots.svg';
import SeatsIcon from './SeatsIcon.svg';
import ScreenIcon from './ScreenIcon.svg';
import Seat from './Seat.svg';
export {DashboardIcon, MediaIcon, WatchIcon, MoreIcon,SearchIcon,BackIcon,PlayIcon,CloseIcon,Dots,SeatsIcon,ScreenIcon,Seat};
